package_name: durin
genshin_id: 10000101
key: durin
action_param_keys:
    low_plunge:
        - param: "collision"
    high_plunge:
        - param: "collision"
skill_data_mapping:
    attack:
        attack_1:
            - 0 # 1-Hit DMG|{param0:F1P}
        attack_2:
            - 1 # 2-Hit DMG|{param1:F1P}
        attack_3:
            - 2 # 3-Hit DMG|{param2:F1P} x2
        attack_4:
            - 3 # 4-Hit DMG|{param3:F1P}
        charge:
            - 4 # Charged Attack DMG|{param4:F1P}
        collision:
            - 5 # Plunge DMG|{param5:F1P}
        lowPlunge:
            - 6 # Low Plunge DMG|{param6:P}
        highPlunge:
            - 7 # High Plunge DMG|{param7:P}

    skill:
        skillPurity:
            - 0 # Confirmation of Purity DMG|{param0:P}
        skillDenial1:
            - 1 # Denial of Darkness Hit 1|{param1:P}
        skillDenial2:
            - 2 # Denial of Darkness Hit 2|{param2:P}
        skillDenial3:
            - 3 # Denial of Darkness Hit 3|{param3:P}
        energyRegen:
            - 4 # Energy Regeneration|{param4}

    burst:
        burstPurity1:
            - 0 # Purity Hit 1|{param0:P}
        burstPurity2:
            - 1 # Purity Hit 2|{param1:P}
        burstPurity3:
            - 2 # Purity Hit 3|{param2:P}
        burstDarkness1:
            - 3 # Darkness Hit 1|{param3:P}
        burstDarkness2:
            - 4 # Darkness Hit 2|{param4:P}
        burstDarkness3:
            - 5 # Darkness Hit 3|{param5:P}
        dragonWhiteFlame:
            - 6 # Dragon of White Flame DMG|{param6:P}
        dragonDarkDecay:
            - 7 # Dragon of Dark Decay DMG|{param7:P}

documentation:
    fields_data:
        - fields: [.durin.state]
          desc: Current state - "confirmation" or "denial"
        - fields: [.durin.denial]
          desc: Evaluates to true if in Denial of Darkness state
        - fields: [.durin.confirmation]
          desc: Evaluates to true if in Confirmation of Purity state
        - fields: [.durin.dragon-white-flame]
          desc: Evaluates to true if Dragon of White Flame is active
        - fields: [.durin.dragon-dark-decay]
          desc: Evaluates to true if Dragon of Dark Decay is active
        - fields: [.durin.primordial-fusion-stacks]
          desc: Current number of A4 Primordial Fusion stacks
        - fields: [.durin.hexerei]
          desc: Evaluates to true if Durin is in Hexerei mode
        - fields: [.durin.cycle-stacks]
          desc: Current number of C1 Cycle of Enlightenment stacks for active character
